<#
.SYNOPSIS
    Generates the pass-through layer for the nvcuda.dll proxy.

.DESCRIPTION
    nvcuda.dll exports several hundred functions whose signatures are mostly
    undocumented, so the proxy forwards them with register-exact assembly tail
    jumps - the same technique used for the NvTool* exports of the NVENC shim.

    A small set of entry points is intercepted in C instead, because those are
    the ones mxavcaacplug.dll checks and reports on: device enumeration, compute
    capability and context lifetime. Those names are excluded from the generated
    assembly so the C definitions can own them.

    Emits into src/generated/:
        nvcuda_thunks.asm    one thunk per forwarded export
        nvcuda_shim.def      the full export table, ordinals preserved
        nvcuda_names.h       name table + slot indices for the C side
#>
[CmdletBinding()]
param(
    [string] $Dll = "$env:SystemRoot\System32\nvcuda.dll"
)

$ErrorActionPreference = 'Stop'

# Implemented in C, so not emitted as blind thunks.
$Intercepted = @(
    'cuInit',
    'cuDeviceGetCount',
    'cuDeviceGet',
    'cuDeviceGetName',
    'cuDeviceComputeCapability',
    'cuCtxCreate',      'cuCtxCreate_v2',
    'cuCtxDestroy',     'cuCtxDestroy_v2',
    'cuCtxPopCurrent',  'cuCtxPopCurrent_v2',
    'cuCtxPushCurrent', 'cuCtxPushCurrent_v2'
)

$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'src\generated'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vs = & $vswhere -latest -property installationPath
$dumpbin = Get-ChildItem "$vs\VC\Tools\MSVC" -Directory |
           Sort-Object Name -Descending |
           ForEach-Object { Join-Path $_.FullName 'bin\Hostx64\x64\dumpbin.exe' } |
           Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $dumpbin) { throw 'dumpbin.exe not found' }

Write-Host "Reading exports from $Dll"
$raw = & $dumpbin /exports $Dll 2>&1

# "  ordinal hint RVA  name"  - forwarded exports have no RVA and are skipped.
$exports = @()
foreach ($line in $raw) {
    if ($line -match '^\s+(\d+)\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(\S+)\s*$') {
        $exports += [pscustomobject]@{ Ordinal = [int]$Matches[1]; Name = $Matches[2] }
    }
}
if ($exports.Count -eq 0) { throw 'no exports parsed' }
Write-Host "  $($exports.Count) exports"

$forwarded = $exports | Where-Object { $Intercepted -notcontains $_.Name }
Write-Host "  $($forwarded.Count) forwarded in assembly, $($exports.Count - $forwarded.Count) intercepted in C"

# ---- nvcuda_names.h ------------------------------------------------------
$h = [System.Text.StringBuilder]::new()
[void]$h.AppendLine('// GENERATED by scripts/gen_cuda_thunks.ps1 - do not edit.')
[void]$h.AppendLine('#ifndef NVCUDA_NAMES_H')
[void]$h.AppendLine('#define NVCUDA_NAMES_H')
[void]$h.AppendLine("#define VNC_FORWARD_COUNT $($forwarded.Count)")
[void]$h.AppendLine('static const char *const g_vnc_names[VNC_FORWARD_COUNT] = {')
foreach ($e in $forwarded) { [void]$h.AppendLine("    `"$($e.Name)`",") }
[void]$h.AppendLine('};')
[void]$h.AppendLine('#endif')
Set-Content (Join-Path $outDir 'nvcuda_names.h') $h.ToString() -Encoding ASCII

# ---- nvcuda_thunks.asm ---------------------------------------------------
$a = [System.Text.StringBuilder]::new()
[void]$a.AppendLine('; GENERATED by scripts/gen_cuda_thunks.ps1 - do not edit.')
[void]$a.AppendLine(';')
[void]$a.AppendLine('; Register-exact tail jumps into the real nvcuda.dll. Signature-agnostic,')
[void]$a.AppendLine('; which matters because most of these are undocumented.')
[void]$a.AppendLine('OPTION CASEMAP:NONE')
[void]$a.AppendLine('EXTERN g_vnc_fns:QWORD')
[void]$a.AppendLine('EXTERN vnc_resolve:PROC')
[void]$a.AppendLine('.CODE')
[void]$a.AppendLine('CUTHUNK MACRO fname:REQ, idx:REQ')
[void]$a.AppendLine('    LOCAL ready, failed')
[void]$a.AppendLine('PUBLIC fname')
[void]$a.AppendLine('fname PROC FRAME')
[void]$a.AppendLine('    sub     rsp, 88h')
[void]$a.AppendLine('    .ALLOCSTACK 88h')
[void]$a.AppendLine('    .ENDPROLOG')
[void]$a.AppendLine('    mov     rax, QWORD PTR [g_vnc_fns + (idx) * 8]')
[void]$a.AppendLine('    test    rax, rax')
[void]$a.AppendLine('    jnz     ready')
[void]$a.AppendLine('    mov     QWORD PTR [rsp+20h], rcx')
[void]$a.AppendLine('    mov     QWORD PTR [rsp+28h], rdx')
[void]$a.AppendLine('    mov     QWORD PTR [rsp+30h], r8')
[void]$a.AppendLine('    mov     QWORD PTR [rsp+38h], r9')
[void]$a.AppendLine('    movdqa  XMMWORD PTR [rsp+40h], xmm0')
[void]$a.AppendLine('    movdqa  XMMWORD PTR [rsp+50h], xmm1')
[void]$a.AppendLine('    movdqa  XMMWORD PTR [rsp+60h], xmm2')
[void]$a.AppendLine('    movdqa  XMMWORD PTR [rsp+70h], xmm3')
[void]$a.AppendLine('    mov     ecx, idx')
[void]$a.AppendLine('    call    vnc_resolve')
[void]$a.AppendLine('    movdqa  xmm3, XMMWORD PTR [rsp+70h]')
[void]$a.AppendLine('    movdqa  xmm2, XMMWORD PTR [rsp+60h]')
[void]$a.AppendLine('    movdqa  xmm1, XMMWORD PTR [rsp+50h]')
[void]$a.AppendLine('    movdqa  xmm0, XMMWORD PTR [rsp+40h]')
[void]$a.AppendLine('    mov     r9,  QWORD PTR [rsp+38h]')
[void]$a.AppendLine('    mov     r8,  QWORD PTR [rsp+30h]')
[void]$a.AppendLine('    mov     rdx, QWORD PTR [rsp+28h]')
[void]$a.AppendLine('    mov     rcx, QWORD PTR [rsp+20h]')
[void]$a.AppendLine('    test    rax, rax')
[void]$a.AppendLine('    jz      failed')
[void]$a.AppendLine('ready:')
[void]$a.AppendLine('    add     rsp, 88h')
[void]$a.AppendLine('    jmp     rax')
[void]$a.AppendLine('failed:')
[void]$a.AppendLine('    add     rsp, 88h')
[void]$a.AppendLine('    mov     eax, 304')   # CUDA_ERROR_OPERATING_SYSTEM
[void]$a.AppendLine('    ret')
[void]$a.AppendLine('fname ENDP')
[void]$a.AppendLine('ENDM')
[void]$a.AppendLine('')
$i = 0
foreach ($e in $forwarded) { [void]$a.AppendLine("    CUTHUNK $($e.Name), $i"); $i++ }
[void]$a.AppendLine('END')
Set-Content (Join-Path $outDir 'nvcuda_thunks.asm') $a.ToString() -Encoding ASCII

# ---- nvcuda_shim.def -----------------------------------------------------
$d = [System.Text.StringBuilder]::new()
[void]$d.AppendLine('; GENERATED by scripts/gen_cuda_thunks.ps1 - do not edit.')
[void]$d.AppendLine('LIBRARY nvcuda')
[void]$d.AppendLine('EXPORTS')
foreach ($e in $exports) { [void]$d.AppendLine("    $($e.Name) @$($e.Ordinal)") }
Set-Content (Join-Path $outDir 'nvcuda_shim.def') $d.ToString() -Encoding ASCII

Write-Host "Wrote nvcuda_thunks.asm, nvcuda_shim.def, nvcuda_names.h to $outDir"
